spring:
  profiles:
    default: local
---
spring:
  profiles:
    activate:
      on-profile: dev


---
spring:
  profiles:
    activate:
      on-profile: local

---
spring:
  profiles:
    activate:
      on-profile: prod