
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
  datasource:
    # jdbc:postgresql://<hostname>:<port>/<database>?useSSL=false
    #url: jdbc:postgresql://localhost:5432/okr-draft?useSSL=false
    url: jdbc:postgresql://localhost:5432/okr?useSSL=false

    # The username of the Postgres User of the OKR Tool.
    username: admin

    # The password of the Postgres User of the OKR Tool.
    password: admin

  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: http://localhost:9090/realms/springtest/protocol/openid-connect/certs
          issuer-uri: http://localhost:9090/realms/springtest
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/springtest
        registration:
          keycloak:
            client-id: spring-test
            # client-id: client ??
            client-secret: VYBPVRDOmGkQPVWHPyJh5hQUajYhsV2u
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
            scope:
              - openid
              - profile
              - offline_access


keycloak:
  realm: springtest
  # realm: realm ??
  resource: spring-test
  # resource: client ??
  auth-server-url: http://localhost:9090/
  # auth-server-url: http://??? ???url:port/
  credentials:
    secret: VYBPVRDOmGkQPVWHPyJh5hQUajYhsV2u
  use-resource-role-mappings: true
  bearer-only: true
  ssl-required: external
  principal-attribute: preferred_username