
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        globally_quoted_identifiers: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://130.162.158.186:3306/googlecalendar
    username: local
    password: adminadmin

  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-set-uri: https://okrbiz.com:8080/realms/5240/protocol/openid-connect/certs
          issuer-uri: https://okrbiz.com:8080/realms/5240
      client:
        provider:
          keycloak:
            issuer-uri: https://okrbiz.com:8080/realms/5240
        registration:
          keycloak:
            client-id: 5240-client
            # client-id: client ??
            client-secret: M43VdyVXcJUABl8hegNZDdeE5lGmgrwJ
            authorization-grant-type: authorization_code
            redirect-uri: https://okrbiz.com/login/oauth2/code/keycloak
            scope:
              - openid
              - profile
              - offline_access


keycloak:
  realm: springtest
  # realm: realm ??
  resource: spring-test
  # resource: client ??
  auth-server-url: https://okrbiz.com:8080/
  # auth-server-url: http://??? ???url:port/
  credentials:
    secret: M43VdyVXcJUABl8hegNZDdeE5lGmgrwJ
  use-resource-role-mappings: true
  bearer-only: true
  ssl-required: external
  principal-attribute: preferred_username

server:
  port: 8000